#!/usr/bin/env python3
"""
public/ → dist/oshima-smart-course.html（配布用の1ファイルHTML）を生成する。

- CSS / JSON / JS をすべて埋め込む（file:// でダブルクリックして開ける、オフラインOK）
- ES module（import/export）と fetch を使わない形に変換する
- 依存: Python 3 標準ライブラリのみ

使い方:  python3 scripts/build_standalone.py   （または npm run build:standalone）
"""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PUB = ROOT / "public"
OUT = ROOT / "dist" / "oshima-smart-course.html"

def read(p): return (PUB / p).read_text(encoding="utf-8")

def main():
    html = read("index.html")
    css = read("style.css")
    planner = read("js/planner.js")
    app = read("js/app.js")
    data = {
        "timetable": json.loads(read("data/timetable.json")),
        "spots": json.loads(read("data/spots.json")),
    }

    # --- JS を非モジュール化 ---
    planner = re.sub(r"^export\s+(const|function|let|class)\s", r"\1 ", planner, flags=re.M)
    app = re.sub(r"^import\s+.*?;\s*$", "", app, flags=re.M)

    # </script> がJS文字列に含まれると壊れるので保険
    def safe(s): return s.replace("</script>", "<\\/script>")
    data_js = "window.__DATA__ = " + json.dumps(data, ensure_ascii=False).replace("</", "<\\/") + ";"

    bundle = "\n".join([
        "<script>",
        "// ---- generated by scripts/build_standalone.py — 編集は public/ 側で行うこと ----",
        data_js,
        "// ---- planner.js ----",
        safe(planner),
        "// ---- app.js ----",
        safe(app),
        "</script>",
    ])

    # --- HTML に埋め込み ---
    n1 = html.count('<link rel="stylesheet" href="style.css">')
    n2 = html.count('<script type="module" src="js/app.js"></script>')
    if n1 != 1 or n2 != 1:
        sys.exit(f"index.html の想定タグが見つかりません (link={n1}, script={n2})")
    html = html.replace('<link rel="stylesheet" href="style.css">', "<style>\n" + css + "\n</style>")
    html = html.replace('<script type="module" src="js/app.js"></script>', bundle)
    html = html.replace("<title>大島スマートコース PoC</title>", "<title>大島スマートコース PoC（スタンドアロン版）</title>")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(html, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")

if __name__ == "__main__":
    main()
