#!/usr/bin/env python3
"""
public/ → dist/oshima-smart-course.html（配布用の1ファイルHTML）を生成する。

- CSS / JSON / JS をすべて埋め込む（file:// でダブルクリックして開ける、オフラインOK）
- ES module（import/export）と fetch を使わない形に変換する
- AI解説・天気はサーバーが無いのでフォールバック表示になる（app.js側で対応済み）
- 依存: Python 3 標準ライブラリのみ

使い方:  python3 scripts/build_standalone.py   （または npm run build:standalone）
※ 事前に `npm run build:css` で public/css/styles.css を生成しておくこと
"""
import base64, json, mimetypes, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PUB = ROOT / "public"
OUT = ROOT / "dist" / "oshima-smart-course.html"

def read(p): return (PUB / p).read_text(encoding="utf-8")

def main():
    html = read("index.html")
    css = read("css/styles.css")
    planner = read("js/planner.js")
    app = read("js/app.js")
    data = {
        "timetable": json.loads(read("data/timetable.json")),
        "spots": json.loads(read("data/spots.json")),
        "ferry": json.loads(read("data/ferry.json")),
        "geo": json.loads(read("data/geo.json")),
    }

    # --- 紹介ビデオ(9MB超)はスタンドアロン版には含めない ---
    html = re.sub(r'\n?\s*<section id="promoVideo".*?</section>', "", html, flags=re.S)
    html = re.sub(r'\s*<a href="#promoVideo"[^>]*>.*?</a>', "", html, flags=re.S)

    # --- 画像(img/…参照)を data URI で埋め込み(オフラインでも表示できるように) ---
    def embed_img(m):
        attr, path = m.group(1), m.group(2)
        f = PUB / path
        if not f.exists():
            return m.group(0)
        mime = mimetypes.guess_type(str(f))[0] or "application/octet-stream"
        b64 = base64.b64encode(f.read_bytes()).decode()
        return f'{attr}="data:{mime};base64,{b64}"'
    html = re.sub(r'(src|href)="(img/[^"]+)"', embed_img, html)
    css = re.sub(r'url\((img/[^)]+)\)', lambda m: f'url(data:{mimetypes.guess_type(m.group(1))[0]};base64,{base64.b64encode((PUB / m.group(1)).read_bytes()).decode()})' if (PUB / m.group(1)).exists() else m.group(0), css)

    # --- JS を非モジュール化 ---
    strip_export = lambda s: re.sub(r"^export\s+(async\s+)?(const|function|let|class)\s", r"\1\2 ", s, flags=re.M)
    planner = strip_export(planner)
    app = strip_export(re.sub(r"^import\s+.*?;\s*$", "", app, flags=re.M))

    # </script> がJS文字列に含まれると壊れるので保険
    def safe(s): return s.replace("</script>", "<\\/script>")
    data_js = "window.__DATA__ = " + json.dumps(data, ensure_ascii=False).replace("</", "<\\/") + ";"

    bundle = "\n".join([
        "<script>",
        "// ---- generated by scripts/build_standalone.py — 編集は public/ 側で行うこと ----",
        data_js,
        "// ---- planner.js ----",
        safe(planner),
        "// ---- app.js ----",
        safe(app),
        "</script>",
    ])

    # --- HTML に埋め込み ---
    n1 = html.count('<link rel="stylesheet" href="css/styles.css">')
    n2 = html.count('<script type="module" src="js/app.js"></script>')
    if n1 != 1 or n2 != 1:
        sys.exit(f"index.html の想定タグが見つかりません (link={n1}, script={n2})")
    html = html.replace('<link rel="stylesheet" href="css/styles.css">', "<style>\n" + css + "\n</style>")
    html = html.replace('<script type="module" src="js/app.js"></script>', bundle)
    html = html.replace("<title>大島スマートコース</title>", "<title>大島スマートコース（スタンドアロン版）</title>")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(html, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")

if __name__ == "__main__":
    main()
